//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DesktopToolbox.rc
//
#define IDS_PROJNAME                    100
#define IDR_DesktopToolbox              100
#define IDD_MAINWINDOW                  101
#define IDD_TOOLBOX                     102
#define IDS_MYBUTTON_DESC               103
#define IDR_myButton                    104
#define IDD_EXIT                        105
#define IDD_EDITDESKTOPNAME             107
#define IDD_SHAREWAREMESSAGE            108
#define IDD_ABOUT                       109
#define IDD_ABOUT25                     110
#define IDD_NAGSCREEN                   111
#define IDD_INFOMESSAGE                 112
#define IDB_MAINWINDOW                  201
#define IDC_BUTTON_CANCEL               201
#define IDI_TASK_ICON                   202
#define IDC_OK                          202
#define IDC_EDIT_DESKTOP_NAME           202
#define IDB_RIGHT_SCREEN                203
#define IDC_EDIT_DESKTOP_COMMENTS       203
#define IDB_HELP                        204
#define IDC_BUTTON_NEW                  204
#define IDB_CLOSE                       205
#define IDC_BUTTON_DELETE               205
#define IDB_HELP_ON                     206
#define IDB_CLOSE_ON                    207
#define IDC_BUTTON_APPLY                207
#define IDC_SELECT                      208
#define IDC_EDIT_KEY                    208
#define IDC_DELIMITER                   208
#define IDC_POINTER                     209
#define IDC_EDIT_COMUTERID              209
#define IDB_TRYING                      210
#define IDC_EDIT_USER_ID                210
#define IDC_ICON_UNLOCK                 211
#define IDC_BUTTON_ORDERING             212
#define IDB_DELIMITER                   212
#define IDB_TRIAL_KEY_UNLOCK            213
#define IDC_TRYING                      213
#define IDB_TRIAL_KEY_LOCK              214
#define IDC_NORMAL                      215
#define IDC_TEXT_MESSAGE                215
#define IDB_LEFT_SCREEN                 216
#define IDC_MESTEXT                     216
#define IDC_CHECK_AS_VISTUAL_DESKTOP    217
#define IDB_EXIT1_ON                    218
#define IDC_DELETE_FROM_STURTUP         219
#define IDB_EXIT1_OFF                   219
#define IDB_WEB_NOTE_OFF                220
#define IDB_WEB_NOTE_ON                 221
#define IDB_WEB_LINK_OFF                222
#define IDB_WEB_LINK_ON                 223
#define IDB_TOOLS_OFF                   224
#define IDB_TOOLS_ON                    225
#define IDB_SCRIPT_ON                   226
#define IDB_SCRIPT_OFF                  227
#define IDB_WRITE_TOOLS_ON              228
#define IDB_WRITE_TOOLS_OFF             229
#define IDI_DOCUMENT_T                  230
#define IDI_GODESKTOP                   230
#define IDB_FOLDER                      231
#define IDB_RUN_SELECTED                232
#define IDR_MENU1                       233
#define IDB_ITEMDEFAULT                 234
#define IDB_ITEMDEFAULT_N               235
#define IDB_CHECK                       236
#define IDB_NEXT                        237
#define IDB_MYFOLDER                    238
#define IDB_DESKTOP_ON                  239
#define IDB_DESKTOP_OFF                 240
#define IDB_MENU_HELP                   241
#define IDB_MENU_ABOUT                  242
#define IDB_MENU_CONFIGURATION          243
#define IDB_MENU_WWW                    244
#define IDB_HELP_B                      245
#define IDB_MENU_KEY                    246
#define IDB_WINDOWS_DESKTOP             248
#define IDB_MYFOLDER_OPEN               249
#define IDB_SHORTCUT                    250
#define IDB_SHORTCUT_URL                251
#define IDB_SHORTCUT_DESKTOP            252
#define IDB_EDIT_NAME_BG                254
#define IDD_MyTooltip                   255
#define IDB_MYFOLDER_EMPTY              257
#define IDB_SHORTCUT_DESKTOP_EMPTY      258
#define IDI_TASK_ABOUT                  259
#define IDI_EDIT_DESKTOP_NAME           260
#define IDB_TRIAL_EXPIRED               261
#define IDB_TITLE_purchase              262
#define IDB_SCREEN_25                   263
#define IDB_OK_OF                       264
#define IDB_OK_ON                       265
#define IDB_KEY_LOCK                    266
#define IDB_KEY_UNLOCK                  267
#define IDI_GODESKTOPWIN                268
#define IDI_GODESKTOPWIN2               269
#define IDI_SETUP                       270
#define IDB_info_but                    271
#define IDI_TASK_START                  273
#define IDI_TASK_ICON_L                 274
#define IDD_CopyMessage                 275
#define IDB_TITLE_COPY_TO               276
#define IDB_NAG_SCREEN                  277
#define IDB_RIGHT_LAYAUT                278
#define IDB_LEFT_LAYAUT                 279
#define IDB_TOP_L                       280
#define IDB_HIDE_BOX                    281
#define IDB_SHOW_BOX                    282
#define IDB_EXIT_MY_DESKTOPTOOLBOX      283
#define IDI_TASK_ICON_N                 284
#define IDB_TOP_SCREEN                  285
#define IDB_WORD_DOCUMENT               288
#define IDB_PDF_DOC                     289
#define IDB_HTML_DOC                    290
#define IDB_TXT_DOC                     291
#define IDB_XLS_DOC                     292
#define IDB_PPT_DOC                     293
#define IDB_JPG_DOC                     294
#define IDB_DBF_DOC                     295
#define ID_POP_CONFIG                   32768
#define ID_POP_TEST2                    32769
#define ID_REGISTRATION                 32769
#define ID_POP_SUBM_TEST                32771
#define ID_POP_SUBM_TEST2               32772
#define ID_POP_VISITOURSITE             32774
#define ID_POP_ABOUTMYDESKTOPTOOLBOX    32775
#define ID_POP_HOWTOUSEMYDESKTOPTOOLBOX 32776
#define ID_POP_CONFIGURATION            32777
#define ID_POP_CHANGINGTITLEINFORMATIONOFTHEDESKTOP 32778
#define ID_POP_SHOWDESKTOPTOOLBOX_RIGHTPANEL 32780
#define ID_POP_SHOWDESKTOPTOOLBOX_LEFTPANEL 32781
#define ID_POP_SHOWDESKTOPTOOLBOX_TOPPANEL 32782
#define ID_POP_SHOWDESKTOPTOOLBOX_HIDEDESKTOPPANEL 32783
#define ID_POP_ARRANGEDESKTOPTOOLBOX_ARRANGEMENT 32784
#define ID_POP_ARRANGEDESKTOPTOOLBOX_SHOW 32785
#define ID_POP_EXITMYDSKTOPTOOLBOX      32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        296
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         218
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
